version: '2'
services:
  contract_observer:
    image: forkdelta/backend
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
      WS_PROVIDER_URL: ${WS_PROVIDER_URL}
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    command: >
      python3 -m app.services.contract_observer

  etherdelta_observer:
    image: forkdelta/backend
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    command: >
      python3 -m app.services.etherdelta_observer

  huey_consumer:
    image: forkdelta/backend
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
    links:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    command: >
      huey_consumer.py app.services.huey_consumer.huey --verbose

  websocket_server:
    image: forkdelta/backend
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: >
      python3 -m app.services.websocket_server

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:4.0-alpine
